apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/onepassword-scim-bridge/charts/op-scim-bridge
  contents:
  - path: .
    git:
      url: https://github.com/giantswarm/op-scim-helm-upstream
      ref: main # TODO: Change to a specific version
    includePaths:
      - charts/op-scim-bridge/**
    newRootPath: charts/op-scim-bridge
