project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: gsoci.azurecr.io
  name: giantswarm/scim
  tag: v0.0.1
  pullPolicy: IfNotPresent

kyvernoPolicyExceptions:
  enabled: false
  namespace: ""

ciliumNetworkPolicy:
  enabled: true

scimsession: ""

op-scim-bridge:
  scim:
    imageRepository: gsoci.azurecr.io/giantswarm/scim

    credentials:
      volume:
        enabled: false
      secrets:
        enabled: true
        name: onepassword-scim-bridge-credentials

    service:
      type: ClusterIP

    ingress:
      enabled: false
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-giantswarm
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - host: "op-scim.local"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: op-scim-tls
          hosts:
            - "op-scim.local"

    # Try to spread the bridge pod and redis. This is fragile because the inner chart has some static labels and some dynamic ones.
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - redis
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - onepassword-scim-bridge
              topologyKey: "kubernetes.io/hostname"

    initContainerSecurityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
          - ALL
      privileged: true
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      seccompProfile:
        type: RuntimeDefault

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsUser: 999
      runAsGroup: 999
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    podSecurityContext:
      fsGroup: 999
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
