project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/scim
  tag: v0.0.1
  pullPolicy: IfNotPresent

kyvernoPolicyExceptions:
  enabled: true
  namespace: ""

op-scim-bridge:
  scim:
    imageRepository: quay.io/giantswarm/scim

    initContainerSecurityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
          - ALL
      privileged: true
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      seccompProfile:
        type: RuntimeDefault

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsUser: 999
      runAsGroup: 999
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    podSecurityContext:
      fsGroup: 999
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
