project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/scim
  tag: v0.0.1
  pullPolicy: IfNotPresent

kyvernoPolicyExceptions:
  enabled: true
  namespace: ""

ciliumNetworkPolicy:
  enabled: false

op-scim-bridge:
  scim:
    imageRepository: quay.io/giantswarm/scim

    service:
      type: ClusterIP

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-giantswarm
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - host: "op-scim.local"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: op-scim-tls
          hosts:
            - "op-scim.local"

    initContainerSecurityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
          - ALL
      privileged: true
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      seccompProfile:
        type: RuntimeDefault

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsUser: 999
      runAsGroup: 999
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    podSecurityContext:
      fsGroup: 999
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
