version: 2.1
orbs:
  architect: giantswarm/architect@5.1.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: package-and-push-chart
        app_catalog: giantswarm-operations-platform-catalog
        app_catalog_test: giantswarm-operations-platform-test-catalog
        chart: '1password-scim-bridge'
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
