name: 1password-scim-bridge
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/scim
  tag: v0.0.1
  pullPolicy: IfNotPresent
