name: &name onepassword-scim-bridge

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/scim
  tag: v0.0.1
  pullPolicy: IfNotPresent

op-scim-bridge:
  scim:
    name: *name
    imageRepository: quay.io/giantswarm/scim
