# The name of this App starts with a number, which K8s doesn't allow in Service names.
# Fullname overrides are set for this chart and subcharts, but if that becomes a problem,
# it might be better to rename the whole App.
name: &name onepassword-scim-bridge

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/scim
  tag: v0.0.1
  pullPolicy: IfNotPresent

op-scim-bridge:
  redis:
    fullnameOverride: onepassword-scim-redis
  scim:
    name: *name
    imageRepository: quay.io/giantswarm/scim
    
    initContainerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    podSecurityContext:
      runAsUser: 999
      runAsGroup: 999
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
