apiVersion: "networking.k8s.io/v1"
kind: NetworkPolicy
metadata:
  name: {{ include "onepassword-scim-bridge-helpers.name" . }}-cnp
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "onepassword-scim-bridge-helpers.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "op-scim-bridge.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
    # Allow egress to redis.                  
    - to:
      - podSelector:
          matchLabels:        
            app.kubernetes.io/name: redis
            app.kubernetes.io/instance: onepassword-scim-bridge
      - ports:
        - port: "6379"
          protocol: TCP
    # Allow DNS resolution.
    - to:
      - podSelector:
          matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: coredns
      - podSelector:
          matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: k8s-dns-node-cache
      - ports:
        - port: "1053"
          protocol: UDP
        - port: "1053"
          protocol: TCP
        - port: "53"
          protocol: UDP
        - port: "53"
          protocol: TCP
---
{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "onepassword-scim-bridge-helpers.name" . }}-cnp
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "onepassword-scim-bridge-helpers.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "op-scim-bridge.selectorLabels" . | nindent 6 }}
  egress:
    # Allow egress to redis.                  
    - toEndpoints:
        - matchLabels:        
            app.kubernetes.io/name: redis
            app.kubernetes.io/instance: onepassword-scim-bridge
      toPorts:
      - ports:
        - port: "6379"
    # Allow DNS resolution.
    - toEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: kube-system
          k8s-app: coredns
      - matchLabels:
          io.kubernetes.pod.namespace: kube-system
          k8s-app: k8s-dns-node-cache
      toPorts:
      - ports:
        - port: "1053"
          protocol: UDP
        - port: "1053"
          protocol: TCP
        - port: "53"
          protocol: UDP
        - port: "53"
          protocol: TCP
{{ end }}
# apiVersion: "networking.k8s.io/v1"
# kind: NetworkPolicy
# metadata:
#   name: {{ include "onepassword-scim-bridge-helpers.name" . }}-cnp
#   namespace: {{ .Release.Namespace }}
#   labels:
#     {{ include "onepassword-scim-bridge-helpers.labels" . | nindent 4 }}
# spec:
#   podSelector:
#     matchLabels:
#       {{- include "op-scim-bridge.selectorLabels" . | nindent 6 }}
#   egress:
#     # Allow egress to redis.                  
#     - toEndpoints:
#         - matchLabels:        
#             app.kubernetes.io/name: redis
#             app.kubernetes.io/instance: onepassword-scim-bridge
#       toPorts:
#       - ports:
#         - port: "6379"
#     # Allow DNS resolution.
#     - toEndpoints:
#       - matchLabels:
#           io.kubernetes.pod.namespace: kube-system
#           k8s-app: coredns
#       - matchLabels:
#           io.kubernetes.pod.namespace: kube-system
#           k8s-app: k8s-dns-node-cache
#       toPorts:
#       - ports:
#         - port: "1053"
#           protocol: UDP
#         - port: "1053"
#           protocol: TCP
#         - port: "53"
#           protocol: UDP
#         - port: "53"
#           protocol: TCP