{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "onepassword-scim-bridge-helpers.name" . }}-cnp
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "onepassword-scim-bridge-helpers.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "op-scim-bridge.selectorLabels" . | nindent 6 }}
  egress:
    # Allow egress to redis.                  
    - toEndpoints:
        - matchLabels:        
            app.kubernetes.io/name: redis
            app.kubernetes.io/instance: onepassword-scim-bridge
      toPorts:
      - ports:
        - port: "6379"
    # Allow DNS resolution.
    - toEndpoints:
        - matchLabels:
            k8s-app: k8s-dns-node-cache
      toPorts:
      - ports:
        - port: "53"
{{ end }}
