apiVersion: v1
kind: Secret
metadata:
  name: {{index .Values "op-scim-bridge" "scim" "credentials" "secrets" "name" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "onepassword-scim-bridge-helpers.labels" . | nindent 4 }}
type: Opaque
data:
  scimsession: {{ .Values.scimsession }}
